version: 2.1
orbs:
  release-management: salesforce/npm-release-management@dev:alpha
  # 1234
workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/test-nut:
          name: nuts-on-linux
      # - release-management/test-nut:
      #     name: nuts-on-windows
      #     os: windows
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          name: node-latest
          node_version: latest
      - release-management/test-package:
          name: node-12
      - release-management/release-package:
          sign: true
          github-release: true
          requires:
            - node-latest
          filters:
            branches:
              only: main
  test-ts-update:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/test-ts-update
