name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  nuts:
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@sm/fix-retries
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
      retries: 2
